 // code: translation language code (MyMemory/Google style)
  // speech: BCP-47 locale used for the Web Speech Recognition API
  const LANGUAGES = [
    { code: 'af', speech: 'af-ZA', name: 'Afrikaans' },
    { code: 'sq', speech: 'sq-AL', name: 'Albanian' },
    { code: 'am', speech: 'am-ET', name: 'Amharic' },
    { code: 'ar', speech: 'ar-SA', name: 'Arabic' },
    { code: 'hy', speech: 'hy-AM', name: 'Armenian' },
    { code: 'az', speech: 'az-AZ', name: 'Azerbaijani' },
    { code: 'eu', speech: 'eu-ES', name: 'Basque' },
    { code: 'be', speech: 'be-BY', name: 'Belarusian' },
    { code: 'bn', speech: 'bn-BD', name: 'Bengali' },
    { code: 'bs', speech: 'bs-BA', name: 'Bosnian' },
    { code: 'bg', speech: 'bg-BG', name: 'Bulgarian' },
    { code: 'ca', speech: 'ca-ES', name: 'Catalan' },
    { code: 'ceb', speech: 'fil-PH', name: 'Cebuano' },
    { code: 'zh-CN', speech: 'zh-CN', name: 'Chinese (Simplified)' },
    { code: 'zh-TW', speech: 'zh-TW', name: 'Chinese (Traditional)' },
    { code: 'co', speech: 'co-FR', name: 'Corsican' },
    { code: 'hr', speech: 'hr-HR', name: 'Croatian' },
    { code: 'cs', speech: 'cs-CZ', name: 'Czech' },
    { code: 'da', speech: 'da-DK', name: 'Danish' },
    { code: 'nl', speech: 'nl-NL', name: 'Dutch' },
    { code: 'en', speech: 'en-US', name: 'English' },
    { code: 'eo', speech: 'eo', name: 'Esperanto' },
    { code: 'et', speech: 'et-EE', name: 'Estonian' },
    { code: 'fi', speech: 'fi-FI', name: 'Finnish' },
    { code: 'fr', speech: 'fr-FR', name: 'French' },
    { code: 'fy', speech: 'fy-NL', name: 'Frisian' },
    { code: 'ka', speech: 'ka-GE', name: 'Georgian' },
    { code: 'de', speech: 'de-DE', name: 'German' },
    { code: 'el', speech: 'el-GR', name: 'Greek' },
    { code: 'gu', speech: 'gu-IN', name: 'Gujarati' },
    { code: 'ht', speech: 'fr-HT', name: 'Haitian Creole' },
    { code: 'ha', speech: 'ha-NE', name: 'Hausa' },
    { code: 'he', speech: 'he-IL', name: 'Hebrew' },
    { code: 'hi', speech: 'hi-IN', name: 'Hindi' },
    { code: 'hu', speech: 'hu-HU', name: 'Hungarian' },
    { code: 'is', speech: 'is-IS', name: 'Icelandic' },
    { code: 'id', speech: 'id-ID', name: 'Indonesian' },
    { code: 'ga', speech: 'ga-IE', name: 'Irish' },
    { code: 'it', speech: 'it-IT', name: 'Italian' },
    { code: 'ja', speech: 'ja-JP', name: 'Japanese' },
    { code: 'jw', speech: 'jv-ID', name: 'Javanese' },
    { code: 'kn', speech: 'kn-IN', name: 'Kannada' },
    { code: 'kk', speech: 'kk-KZ', name: 'Kazakh' },
    { code: 'km', speech: 'km-KH', name: 'Khmer' },
    { code: 'ko', speech: 'ko-KR', name: 'Korean' },
    { code: 'ku', speech: 'ku', name: 'Kurdish' },
    { code: 'ky', speech: 'ky-KG', name: 'Kyrgyz' },
    { code: 'lo', speech: 'lo-LA', name: 'Lao' }, 
    { code: 'lv', speech: 'lv-LV', name: 'Latvian' },
    { code: 'lt', speech: 'lt-LT', name: 'Lithuanian' },
    { code: 'lb', speech: 'lb-LU', name: 'Luxembourgish' },
    { code: 'mk', speech: 'mk-MK', name: 'Macedonian' }, 
    { code: 'mg', speech: 'mg-MG', name: 'Malagasy' },
    { code: 'ms', speech: 'ms-MY', name: 'Malay' }, 
    { code: 'ml', speech: 'ml-IN', name: 'Malayalam' },
    { code: 'mt', speech: 'mt-MT', name: 'Maltese' },
    { code: 'mi', speech: 'mi-NZ', name: 'Maori' },
    { code: 'mr', speech: 'mr-IN', name: 'Marathi' },
    { code: 'mn', speech: 'mn-MN', name: 'Mongolian' },
    { code: 'my', speech: 'my-MM', name: 'Myanmar (Burmese)' },
    { code: 'ne', speech: 'ne-NP', name: 'Nepali' },
    { code: 'no', speech: 'nb-NO', name: 'Norwegian' },
    { code: 'ny', speech: 'ny-MW', name: 'Nyanja (Chichewa)' },
    { code: 'ps', speech: 'ps-AF', name: 'Pashto' },
    { code: 'fa', speech: 'fa-IR', name: 'Persian' },
    { code: 'pl', speech: 'pl-PL', name: 'Polish' },
    { code: 'pt', speech: 'pt-PT', name: 'Portuguese' },
    { code: 'pa', speech: 'pa-IN', name: 'Punjabi' }, 
    { code: 'ro', speech: 'ro-RO', name: 'Romanian' },
    { code: 'ru', speech: 'ru-RU', name: 'Russian' },
    { code: 'sm', speech: 'sm-WS', name: 'Samoan' },
    { code: 'gd', speech: 'gd-GB', name: 'Scots Gaelic' },
    { code: 'sr', speech: 'sr-RS', name: 'Serbian' },
    { code: 'st', speech: 'st-ZA', name: 'Sesotho' },
    { code: 'sn', speech: 'sn-ZW', name: 'Shona' },
    { code: 'sd', speech: 'sd-IN', name: 'Sindhi' },
    { code: 'si', speech: 'si-LK', name: 'Sinhala' },
    { code: 'sk', speech: 'sk-SK', name: 'Slovak' },
    { code: 'sl', speech: 'sl-SI', name: 'Slovenian' },
    { code: 'so', speech: 'so-SO', name: 'Somali' }, 
    { code: 'es', speech: 'es-ES', name: 'Spanish' },
    { code: 'su', speech: 'su-ID', name: 'Sundanese' },
    { code: 'sw', speech: 'sw-KE', name: 'Swahili' },
    { code: 'sv', speech: 'sv-SE', name: 'Swedish' },
    { code: 'tl', speech: 'fil-PH', name: 'Tagalog (Filipino)' },
    { code: 'tg', speech: 'tg-TJ', name: 'Tajik' },
    { code: 'ta', speech: 'ta-IN', name: 'Tamil' },
    { code: 'tt', speech: 'tt-RU', name: 'Tatar' },
    { code: 'te', speech: 'te-IN', name: 'Telugu' },
    { code: 'th', speech: 'th-TH', name: 'Thai' },
    { code: 'tr', speech: 'tr-TR', name: 'Turkish' },
    { code: 'tk', speech: 'tk-TM', name: 'Turkmen' },
    { code: 'uk', speech: 'uk-UA', name: 'Ukrainian' },
    { code: 'ur', speech: 'ur-PK', name: 'Urdu' },
    { code: 'ug', speech: 'ug-CN', name: 'Uyghur' },
    { code: 'uz', speech: 'uz-UZ', name: 'Uzbek' },
    { code: 'vi', speech: 'vi-VN', name: 'Vietnamese' },
    { code: 'cy', speech: 'cy-GB', name: 'Welsh' },
    { code: 'xh', speech: 'xh-ZA', name: 'Xhosa' },
    { code: 'yi', speech: 'yi', name: 'Yiddish' },
    { code: 'yo', speech: 'yo-NG', name: 'Yoruba' },
    { code: 'zu', speech: 'zu-ZA', name: 'Zulu' },
  ];
